//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int numeroCliente { get; set; }
        public int numeroCola { get; set; }
        public string id { get; set; }
        public string nombre { get; set; }
        public System.DateTime horaRegistro { get; set; }
        public string estado { get; set; }
    
        public virtual Cola Cola { get; set; }
    }
}
